### ISSUE TITLE
Feature Request: Validate checks transformers for bad GUIDs

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1419]
example:
```
  "26":
    id: "26"
    taskid: 4cd02f0c-f469-4305-8935-acb3407bcbb5
    type: regular
    task:
      id: 4cd02f0c-f469-4305-8935-acb3407bcbb5
      version: -1
      name: Set start time (string)
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      append: {}
      key:
        simple: Change.StartTime
      stringify: {}
      value:
        complex:
          root: incident
          accessor: timestart
          transformers:
          - operator: 95106edb-a44a-451b-8246-5cbbeeed4ed5
            args:
              Date: {}
              FormatString: {}
```
This should error (just like a script or sub-playbook call) with `95106edb-a44a-451b-8246-5cbbeeed4ed5`
