### ISSUE TITLE
demisto-sdk format thinks a command doesn't have any arguments

### ISSUE THREAD

**Issue by ennozdd** [demisto/demisto-sdk#2473]
`demisto-sdk format -ud -i Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml`

sdk thinks the command "endpoint" has no arguments and sets it in the yml file even though it has 3 arguments already

these are the arguments defined
![image](https://user-images.githubusercontent.com/49711791/201900744-c284bcfa-71cd-4439-8676-f1acd795d301.png)

after `demisto-sdk format -ud`. the last argument "endpoint" is set by the sdk
```
  - arguments:
    - default: false
      description: The sensor ID
      isArray: false
      name: id
      required: false
      secret: false
    - default: true
      description: Query sensors with specified IP address
      isArray: true
      name: ip
      required: false
      secret: false
    - default: false
      description: Query sensors with matching hostname
      isArray: false
      name: hostname
      required: false
      secret: false
    - default: true 
      description: ''
      isArray: true
      name: endpoint # this argument is set by the sdk
      required: true
      secret: false
    deprecated: false
    description: List the CarbonBlack sensors
    execution: false
    name: endpoint

```

https://github.com/demisto/content/blob/master/Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml#L1963

```
(.venv) ➜  content git:(inprogress) ✗ demisto-sdk format -ud -i Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
You are using demisto-sdk 1.7.6.

================= Updating file /home/ennozdd/community/content/Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml =================
Command endpoint has no arguemnts. Setting them: {
    "default": true,
    "description": "",
    "isArray": true,
    "name": "endpoint",
    "required": true,
    "secret": false
}
Updating docker image to: demisto/python3:3.10.8.37233

================= Running validation on modified files =================

Validating Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml as integration
Validating scheme for Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
[ERROR]: Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml: [IN134] - The integration command: endpoint has multiple default arguments: {'endpoint', 'ip'}.

[ERROR]: Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml: [IN105] - The argument '['ip']' of the command 'endpoint' is not configured as default

Validating backwards compatibility for Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
[ERROR]: Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml: [BC104] - Possible backwards compatibility break, Your updates to this file contains changes to a name or an argument of an existing command(s).
Please undo you changes to the following command(s):
endpoint
```
