### ISSUE TITLE
demisto-sdk generate-yml-from-python sets all integrations command arguments of decorated command to required:true 

### ISSUE THREAD

**Issue by ajoga** [demisto/demisto-sdk#2797]
Given an integration command like this:

```
@metadata_collector.command(
    command_name="mrc",
    inputs_list=[
        InputArgument(name="arn", description="arn", required=False),
    ])
def mrc_command(args: Dict[str, Any]) -> CommandResults:
    return 'ok'
``` 

Running `demisto-sdk generate-yml-from-python -fvi mrc.py` renders a mrc.yml with:

```
script:
  commands:
  - deprecated: false
    description: ''
    name: mrc
    arguments:
    - name: arn
      isArray: false
      description: arn
      required: true
      secret: false
      default: false
    outputs: []
```

Notice that we have `required: true`. Here is a test case to reproduce it: https://github.com/ajoga/demisto-sdk/commit/203eb0d277a1d54f1c6238af30c9c3c09931d7a5 

Furthermore, not specifying explicitly that an argument is `required` or not in and `InputArgument` yields `required: true` in an automatically generated yml. It feels a bit surprised as the default value for the property `required` for `InputArgument` is `false` : https://github.com/demisto/content/blob/ecd0b989cd8e38ef1d2385542daeb840f549b060/Packs/Base/Scripts/CommonServerPython/CommonServerPython.py#L10725

I am using the latest sdk version to date, 1.10.4.
