### ISSUE TITLE
Mirroring Settings with Generate Python File

### ISSUE THREAD

**Issue by 1Bishop** [demisto/demisto-sdk#3169]
Hi, I was looking through the documentation and trying to set up a 2-way sync with a custom integration. I've been using the [generate yaml from python process](https://xsoar.pan.dev/docs/integrations/yml-from-python-code-gen) when building the integration, but i don't see support for [isremotesync settings](https://xsoar.pan.dev/docs/integrations/mirroring_integration#required-parameters) in the `YMLMetadataCollector`:

```yaml 
  isfetch: true
  ismappable: true
  isremotesyncin: true
  isremotesyncout: true
``` 

Is it possible to add this functionality?
